services:
  backend:
    image: ${DOCKERHUB_USERNAME}/todo-app-backend:latest
    build:
      context: ./BE-Todo
      dockerfile: Dockerfile
    container_name: todo-app-backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@${VM4_PRIVATE_IP}:27017,${VM2_PRIVATE_IP}:27017,${VM3_PRIVATE_IP}:27017/ts-crud?replicaSet=rs0&authSource=admin
    depends_on:
      mongo-secondary:
        condition: service_healthy
    networks:
      - todo-network
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:8000/health || exit 1" ]
      interval: 30s
      timeout: 5s
      retries: 3

  mongo-secondary:
    image: mongo:7
    container_name: mongodb
    restart: always
    command: >
      mongod --replSet rs0
             --keyFile /etc/mongo-keyfile
             --bind_ip_all
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./mongo-keyfile:/etc/mongo-keyfile:ro
    networks:
      - todo-network
    healthcheck:
      test: [ "CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping').ok" ]
      interval: 15s
      timeout: 5s
      retries: 5

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: always
    pid: host
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - "9100:9100"
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge

volumes:
  mongo_data:
