version: '3.8'

services:
  backend:
    build: .
    container_name: todo-backend
    ports:
      - "8000:8000"
    # Nạp file .env vào trong container:
    env_file:
      - .env
    # Ghi đè MONGO_URI vì khi chạy trong docker, backend phải kết nối sang container 'mongodb' chứ không phải 'localhost'
    environment:
      - MONGO_URI=mongodb://admin:240901@mongodb:27017/ts-crud?authSource=admin
    depends_on:
      - mongodb
    restart: always

  mongodb:
    image: mongo:latest
    container_name: todo-mongodb

    environment:
      # Thiết lập tài khoản root admin cho Mongo khớp với trong file .env của bạn
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=240901
    volumes:
      - mongo_data:/data/db
    restart: always

volumes:
  mongo_data:
