name: Deploy Backend

on:
  push:
    branches: ["main"]
    paths:
      - 'BE-Todo/**'
      - 'docker-compose.worker.yml'
      - '.github/workflows/backend.yml'

jobs:
  build-backend:
    uses: ./.github/workflows/build-and-push.yml
    with:
      build_mode: 'compose'
      compose_file: 'docker-compose.worker.yml'
      service: 'backend'
    secrets: inherit

  deploy-backend:
    needs: build-backend
    strategy:
      matrix:
        include:
          - vm: vm2
            runs_on: '["self-hosted","linux","vm2"]'
            env: ENV_FILE_VM
            private_ip: VM2_PRIVATE_IP
          - vm: vm3
            runs_on: '["self-hosted","linux","vm3"]'
            env: ENV_FILE_VM
            private_ip: VM3_PRIVATE_IP

    runs-on: ${{ fromJson(matrix.runs_on) }}
    steps:
      - uses: actions/checkout@v4

      - name: Update project source
        run: |
          cd ~/project/Todo_App
          git fetch --all
          git reset --hard origin/main
          
      - name: Create .env
        run: |
          cat << 'EOF' | sed 's/^[[:space:]]*//' > ~/project/Todo_App/.env
          ${{ secrets.ENV_FILE_VM }}
          BIND_IP=${{ secrets[matrix.private_ip] }}
          DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}
          VM1_PRIVATE_IP=${{ secrets.VM1_PRIVATE_IP }}
          VM2_PRIVATE_IP=${{ secrets.VM2_PRIVATE_IP }}
          VM3_PRIVATE_IP=${{ secrets.VM3_PRIVATE_IP }}
          VM4_PRIVATE_IP=${{ secrets.VM4_PRIVATE_IP }}
          VM5_PRIVATE_IP=${{ secrets.VM5_PRIVATE_IP }}
          VM_PUBLIC_IP=${{ secrets.VM_PUBLIC_IP }}
          EOF
          
          sed -i -e '/^BACKEND_TAG=/d' -e '/^STATIC_TAG=/d' ~/project/Todo_App/.env.tags 2>/dev/null || touch ~/project/Todo_App/.env.tags
          printf "BACKEND_TAG=v${{ github.run_number }}\nSTATIC_TAG=latest\n" >> ~/project/Todo_App/.env.tags
          cat ~/project/Todo_App/.env.tags >> ~/project/Todo_App/.env

      - name: Deploy ${{ matrix.vm }}
        run: |
          cd ~/project/Todo_App
          echo "------------------------------------------------------------"
          echo "Deployment Info:"
          echo "  VM Name: ${{ matrix.vm }}"
          echo "  Target IP (Secret Name): ${{ matrix.private_ip }}"
          echo "  Host IP: $(hostname -I | awk '{print $1}')"
          echo "------------------------------------------------------------"
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
          
          docker compose -f docker-compose.worker.yml pull backend
          docker compose -f docker-compose.worker.yml up -d --force-recreate backend

          docker image prune -af --filter "until=24h"
